### ISSUE TITLE
Автоматическая поддержка домена .ygg в Линуксе

### ISSUE THREAD

**Issue by Kashcheyeu** [Revertron/wyrd#14]
Можно ли указать в NetworkManager предоставляемые вами IP-адреса рабочих серверов так, чтобы операционная система стала автоматически преобразовывать домен .ygg? Подключение к Интернету производится через IPv4.

**Comment by Revertron** [comment]
Вполне возможно, что можно.
Надо изучать документацию по NetworkManager и вашей ОС.

**Comment by Kashcheyeu** [comment]
Могли бы вы помочь с этим?

**Comment by Revertron** [comment]
Нет, я не пользуюсь NetworkManager и вообще десктопным линуксом.

**Comment by Kashcheyeu** [comment]
Решение нашлось на [howto.ygg](http://[300:529f:150c:eafe::6]/doku.php?id=yggdrasil:dns_client_configure). Указал только один сервер, расположенный в Дюссельдорфе, потому что с другими ничего не работает.

 В файл /etc/systemd/resolved.conf нужно прописать следующее:
```
[Resolve]
DNS=300:4523::53
Domains=~.
```

и выполнить перезапуск службы systemd-resolved:

`sudo systemctl restart systemd-resolved`

**Comment by Revertron** [comment]
> потому что с другими ничего не работает

Это очень странно. Можешь попробовать для всех серверов запустить `nslookup google.com 300:4523::53`? Тут IP надо разные подставить.

**Comment by Kashcheyeu** [comment]
```
$ nslookup tut.by 301:2522::53
Server:		301:2522::53
Address:	301:2522::53#53

Non-authoritative answer:
Name:	tut.by
Address: 178.172.160.3
Name:	tut.by
Address: 178.172.160.4
Name:	tut.by
Address: 178.172.160.5
Name:	tut.by
Address: 178.172.160.2
Name:	tut.by
Address: 2a0a:7d80::d
Name:	tut.by
Address: 2a0a:7d80::a
Name:	tut.by
Address: 2a0a:7d80::b
Name:	tut.by
Address: 2a0a:7d80::c
```
```
$ nslookup tut.by 301:2923::53
;; connection timed out; no servers could be reached
```
```
$ nslookup tut.by 300:4523::53
Server:		300:4523::53
Address:	300:4523::53#53

Non-authoritative answer:
Name:	tut.by
Address: 178.172.160.2
Name:	tut.by
Address: 178.172.160.5
Name:	tut.by
Address: 178.172.160.3
Name:	tut.by
Address: 178.172.160.4
Name:	tut.by
Address: 2a0a:7d80::c
Name:	tut.by
Address: 2a0a:7d80::b
Name:	tut.by
Address: 2a0a:7d80::d
Name:	tut.by
Address: 2a0a:7d80::a
```
```
$ nslookup tut.by 303:8b1a::53
Server:		303:8b1a::53
Address:	303:8b1a::53#53

Non-authoritative answer:
Name:	tut.by
Address: 178.172.160.3
Name:	tut.by
Address: 178.172.160.4
Name:	tut.by
Address: 178.172.160.5
Name:	tut.by
Address: 178.172.160.2
Name:	tut.by
Address: 2a0a:7d80::b
Name:	tut.by
Address: 2a0a:7d80::a
Name:	tut.by
Address: 2a0a:7d80::d
Name:	tut.by
Address: 2a0a:7d80::c
```

**Comment by Revertron** [comment]
Вот как раз с `301:2923::53` была проблема пару часов назад.
А остальное выглядит нормально, должно работать.
