### ISSUE TITLE
Chrome не резолвит домены

### ISSUE THREAD

**Issue by testeron211** [Revertron/wyrd#15]
Добрый день, хром не резолвит домены, хотя остальные браузеры это делают замечательно. Secure DNS выключен.

Windows 7 SP1 x64 / Chrome 89.0.4389.82 x64

![image](https://user-images.githubusercontent.com/33691558/111142269-8735bf80-8595-11eb-8ff9-cf93644954a9.png)

**Comment by Revertron** [comment]
Я не в курсе, почему Chrome так делает, я им не пользуюсь.
`nslookup` ведь резолвит домены? Если да, то проблема именно в Хроме.

**Comment by testeron211** [comment]
> Я не в курсе, почему Chrome так делает, я им не пользуюсь.
> `nslookup` ведь резолвит домены? Если да, то проблема именно в Хроме.

Именно, только chrome делает такие выкрутасы

**Comment by Revertron** [comment]
Можно попробовать пооткрывать только IPv6 сайты. Интересно, как он с ними работает?
Но я предполагаю, что они проверяют наличие роута, который используется для IPv6 (2001::/16), и если его нет, то не делают DNS-запросов типа AAAA. Таким поведением страдают уже многие продукты. Firefox для Android тоже так себя ведёт вроде.
