### ISSUE TITLE
Feature request: subdomain validation

### ISSUE THREAD

**Issue by podivilov** [Revertron/wyrd#2]
Someone who don't holds domain name like git.medium can reserve domain name www.git.medium or the same, so this is a potentially a security issue.

**Comment by Revertron** [comment]
Current domain validation is approving only of second level domains.
I've added `r.git.medium` to my nodeinfo, and this is the log of wyrd crawler:
```
r.git.medium is not valid domain, ignoring
```

**Comment by podivilov** [comment]
@Revertron, why not to use wildcard for *.git.medium instead of ignoring?
