### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by nxshock** [Revertron/wyrd#3]
Предположим, что есть домен `pupok.ygg`, который желают иметь Вася и Петя. Оба в приблизительно одно время (допустим, с разницей в 2 минуты) прописывают себе в конфиг данный адрес.

Исходя из предположения о том, что crawler'ы индексируют сеть в случайном порядке (поправьте, если не прав), информация в сети о владельце доменаразделится на два лагеря.

Как предполагается бороться с данной проблемой?

**Comment by Revertron** [comment]
Да, в текущей версии такое разделение возможно. В ней ещё не реализованы некоторые важные моменты, например "протухание" доменов, владельцев которых нет в сети месяц. И нет подтверждения владения через PoW. Вот когда PoW будет введён в эксплуатацию, это сильно уменьшит вероятность коллизий.

**Comment by L0stedMind** [comment]
Что означает PoW?

**Comment by Revertron** [comment]
@L0stedMind это [Proof of Work](https://en.wikipedia.org/wiki/Proof_of_work). То есть, осуществление какой-то работы для доказательства. В простонародии - майнинг.

**Comment by L0stedMind** [comment]
@Revertron спасибо за объяснение)

**Comment by nxshock** [comment]
PoW никак не решит проблему. А внедрение блокчейнов только создаст новые.
